// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/compiler_api.dart';
import 'api/component_api.dart';
import 'api/error_api.dart';
import 'api/js_engine.dart';
import 'api/layout_api.dart';
import 'api/poc_render.dart';
import 'api/simple.dart';
import 'api/vnode_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1228341687;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_qiqiaoban',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  int crateApiJsEngineActiveEngineCount();

  Future<String> crateApiComponentApiCallComponentMethod({
    required int componentId,
    required String method,
    required String argsJson,
  });

  Future<String> crateApiCompilerApiCompileAndCreateComponent({
    required String template,
    required String script,
  });

  Future<String> crateApiCompilerApiCompileTemplate({required String template});

  Future<String> crateApiVnodeApiComputeLayoutFromVnode({
    required String vnodeJson,
    required double width,
    required double height,
  });

  Future<String> crateApiComponentApiCreateComponent({required String jsCode});

  Future<int> crateApiJsEngineCreateJsEngine({
    int? memoryLimitMb,
    int? maxStackSizeKb,
  });

  int crateApiLayoutApiCreateLayoutTree();

  Future<void> crateApiComponentApiDestroyComponent({required int componentId});

  Future<void> crateApiComponentApiDestroyComponentEngine();

  Future<void> crateApiJsEngineDestroyJsEngine({required int engineId});

  void crateApiLayoutApiDestroyLayoutTree({required int treeId});

  Future<void> crateApiPocRenderDestroyPocEngine();

  Future<void> crateApiVnodeApiDestroyVnodeEngine();

  Future<String> crateApiVnodeApiDiffVnodes({
    required String oldJson,
    required String newJson,
  });

  Future<String> crateApiVnodeApiDispatchEvent({required String eventJson});

  Future<String> crateApiComponentApiEvalComponentJs({required String code});

  Future<String> crateApiJsEngineEvalJs({
    required int engineId,
    required String code,
  });

  Future<String> crateApiVnodeApiEvalVnodeJs({required String code});

  Future<String> crateApiComponentApiGetComponentVnode({
    required int componentId,
  });

  Future<String> crateApiErrorApiGetRecentErrors();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  BigInt crateApiLayoutApiLayoutAddContainer({
    required int treeId,
    required Uint64List childrenIds,
    String? flexDirection,
    String? flexWrap,
    String? justifyContent,
    String? alignItems,
    double? gapRow,
    double? gapColumn,
    double? width,
    double? height,
    double? minWidth,
    double? minHeight,
    double? maxWidth,
    double? maxHeight,
    double? flexGrow,
    double? flexShrink,
    double? paddingTop,
    double? paddingRight,
    double? paddingBottom,
    double? paddingLeft,
    double? marginTop,
    double? marginRight,
    double? marginBottom,
    double? marginLeft,
  });

  BigInt crateApiLayoutApiLayoutAddNode({
    required int treeId,
    double? width,
    double? height,
    double? minWidth,
    double? minHeight,
    double? maxWidth,
    double? maxHeight,
    double? flexGrow,
    double? flexShrink,
    double? paddingTop,
    double? paddingRight,
    double? paddingBottom,
    double? paddingLeft,
    double? marginTop,
    double? marginRight,
    double? marginBottom,
    double? marginLeft,
  });

  void crateApiLayoutApiLayoutCompute({
    required int treeId,
    required BigInt rootId,
    required double width,
    required double height,
  });

  Float64List crateApiLayoutApiLayoutGetResult({
    required int treeId,
    required BigInt nodeId,
  });

  Future<String> crateApiVnodeApiParseVnodeFromJs({required String jsCode});

  Future<QBError> crateApiErrorApiQbErrorCompile({required String message});

  Future<QBError> crateApiErrorApiQbErrorRender({
    required String message,
    int? componentId,
  });

  Future<QBError> crateApiErrorApiQbErrorRuntime({
    required String message,
    int? componentId,
  });

  Future<RenderNode> crateApiPocRenderRenderFromJs({
    required String jsCode,
    required double viewportWidth,
    required double viewportHeight,
  });

  Future<List<RenderNode>> crateApiVnodeApiRenderVnodeFromJs({
    required String jsCode,
    required double viewportWidth,
    required double viewportHeight,
  });

  Future<List<RenderNode>> crateApiVnodeApiRenderVnodeFromJson({
    required String vnodeJson,
    required double viewportWidth,
    required double viewportHeight,
  });

  String crateApiSimpleRustCoreVersion();

  Future<String> crateApiErrorApiSafeCompileTemplate({
    required String template,
  });

  Future<PlatformInt64> crateApiSimpleSumToN({required PlatformInt64 n});

  Stream<int> crateApiSimpleTickStream({required int count});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  int crateApiJsEngineActiveEngineCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiJsEngineActiveEngineCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJsEngineActiveEngineCountConstMeta =>
      const TaskConstMeta(debugName: "active_engine_count", argNames: []);

  @override
  Future<String> crateApiComponentApiCallComponentMethod({
    required int componentId,
    required String method,
    required String argsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(componentId, serializer);
          sse_encode_String(method, serializer);
          sse_encode_String(argsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiComponentApiCallComponentMethodConstMeta,
        argValues: [componentId, method, argsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComponentApiCallComponentMethodConstMeta =>
      const TaskConstMeta(
        debugName: "call_component_method",
        argNames: ["componentId", "method", "argsJson"],
      );

  @override
  Future<String> crateApiCompilerApiCompileAndCreateComponent({
    required String template,
    required String script,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(template, serializer);
          sse_encode_String(script, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCompilerApiCompileAndCreateComponentConstMeta,
        argValues: [template, script],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompilerApiCompileAndCreateComponentConstMeta =>
      const TaskConstMeta(
        debugName: "compile_and_create_component",
        argNames: ["template", "script"],
      );

  @override
  Future<String> crateApiCompilerApiCompileTemplate({
    required String template,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(template, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCompilerApiCompileTemplateConstMeta,
        argValues: [template],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompilerApiCompileTemplateConstMeta =>
      const TaskConstMeta(
        debugName: "compile_template",
        argNames: ["template"],
      );

  @override
  Future<String> crateApiVnodeApiComputeLayoutFromVnode({
    required String vnodeJson,
    required double width,
    required double height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vnodeJson, serializer);
          sse_encode_f_64(width, serializer);
          sse_encode_f_64(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVnodeApiComputeLayoutFromVnodeConstMeta,
        argValues: [vnodeJson, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVnodeApiComputeLayoutFromVnodeConstMeta =>
      const TaskConstMeta(
        debugName: "compute_layout_from_vnode",
        argNames: ["vnodeJson", "width", "height"],
      );

  @override
  Future<String> crateApiComponentApiCreateComponent({required String jsCode}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jsCode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiComponentApiCreateComponentConstMeta,
        argValues: [jsCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComponentApiCreateComponentConstMeta =>
      const TaskConstMeta(debugName: "create_component", argNames: ["jsCode"]);

  @override
  Future<int> crateApiJsEngineCreateJsEngine({
    int? memoryLimitMb,
    int? maxStackSizeKb,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_32(memoryLimitMb, serializer);
          sse_encode_opt_box_autoadd_u_32(maxStackSizeKb, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJsEngineCreateJsEngineConstMeta,
        argValues: [memoryLimitMb, maxStackSizeKb],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJsEngineCreateJsEngineConstMeta =>
      const TaskConstMeta(
        debugName: "create_js_engine",
        argNames: ["memoryLimitMb", "maxStackSizeKb"],
      );

  @override
  int crateApiLayoutApiCreateLayoutTree() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLayoutApiCreateLayoutTreeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLayoutApiCreateLayoutTreeConstMeta =>
      const TaskConstMeta(debugName: "create_layout_tree", argNames: []);

  @override
  Future<void> crateApiComponentApiDestroyComponent({
    required int componentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(componentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiComponentApiDestroyComponentConstMeta,
        argValues: [componentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComponentApiDestroyComponentConstMeta =>
      const TaskConstMeta(
        debugName: "destroy_component",
        argNames: ["componentId"],
      );

  @override
  Future<void> crateApiComponentApiDestroyComponentEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiComponentApiDestroyComponentEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComponentApiDestroyComponentEngineConstMeta =>
      const TaskConstMeta(debugName: "destroy_component_engine", argNames: []);

  @override
  Future<void> crateApiJsEngineDestroyJsEngine({required int engineId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(engineId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJsEngineDestroyJsEngineConstMeta,
        argValues: [engineId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJsEngineDestroyJsEngineConstMeta =>
      const TaskConstMeta(
        debugName: "destroy_js_engine",
        argNames: ["engineId"],
      );

  @override
  void crateApiLayoutApiDestroyLayoutTree({required int treeId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(treeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLayoutApiDestroyLayoutTreeConstMeta,
        argValues: [treeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLayoutApiDestroyLayoutTreeConstMeta =>
      const TaskConstMeta(
        debugName: "destroy_layout_tree",
        argNames: ["treeId"],
      );

  @override
  Future<void> crateApiPocRenderDestroyPocEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPocRenderDestroyPocEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPocRenderDestroyPocEngineConstMeta =>
      const TaskConstMeta(debugName: "destroy_poc_engine", argNames: []);

  @override
  Future<void> crateApiVnodeApiDestroyVnodeEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVnodeApiDestroyVnodeEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVnodeApiDestroyVnodeEngineConstMeta =>
      const TaskConstMeta(debugName: "destroy_vnode_engine", argNames: []);

  @override
  Future<String> crateApiVnodeApiDiffVnodes({
    required String oldJson,
    required String newJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(oldJson, serializer);
          sse_encode_String(newJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVnodeApiDiffVnodesConstMeta,
        argValues: [oldJson, newJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVnodeApiDiffVnodesConstMeta => const TaskConstMeta(
    debugName: "diff_vnodes",
    argNames: ["oldJson", "newJson"],
  );

  @override
  Future<String> crateApiVnodeApiDispatchEvent({required String eventJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(eventJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVnodeApiDispatchEventConstMeta,
        argValues: [eventJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVnodeApiDispatchEventConstMeta =>
      const TaskConstMeta(debugName: "dispatch_event", argNames: ["eventJson"]);

  @override
  Future<String> crateApiComponentApiEvalComponentJs({required String code}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiComponentApiEvalComponentJsConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComponentApiEvalComponentJsConstMeta =>
      const TaskConstMeta(debugName: "eval_component_js", argNames: ["code"]);

  @override
  Future<String> crateApiJsEngineEvalJs({
    required int engineId,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(engineId, serializer);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJsEngineEvalJsConstMeta,
        argValues: [engineId, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJsEngineEvalJsConstMeta =>
      const TaskConstMeta(debugName: "eval_js", argNames: ["engineId", "code"]);

  @override
  Future<String> crateApiVnodeApiEvalVnodeJs({required String code}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVnodeApiEvalVnodeJsConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVnodeApiEvalVnodeJsConstMeta =>
      const TaskConstMeta(debugName: "eval_vnode_js", argNames: ["code"]);

  @override
  Future<String> crateApiComponentApiGetComponentVnode({
    required int componentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(componentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiComponentApiGetComponentVnodeConstMeta,
        argValues: [componentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComponentApiGetComponentVnodeConstMeta =>
      const TaskConstMeta(
        debugName: "get_component_vnode",
        argNames: ["componentId"],
      );

  @override
  Future<String> crateApiErrorApiGetRecentErrors() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiErrorApiGetRecentErrorsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiErrorApiGetRecentErrorsConstMeta =>
      const TaskConstMeta(debugName: "get_recent_errors", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  BigInt crateApiLayoutApiLayoutAddContainer({
    required int treeId,
    required Uint64List childrenIds,
    String? flexDirection,
    String? flexWrap,
    String? justifyContent,
    String? alignItems,
    double? gapRow,
    double? gapColumn,
    double? width,
    double? height,
    double? minWidth,
    double? minHeight,
    double? maxWidth,
    double? maxHeight,
    double? flexGrow,
    double? flexShrink,
    double? paddingTop,
    double? paddingRight,
    double? paddingBottom,
    double? paddingLeft,
    double? marginTop,
    double? marginRight,
    double? marginBottom,
    double? marginLeft,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(treeId, serializer);
          sse_encode_list_prim_u_64_strict(childrenIds, serializer);
          sse_encode_opt_String(flexDirection, serializer);
          sse_encode_opt_String(flexWrap, serializer);
          sse_encode_opt_String(justifyContent, serializer);
          sse_encode_opt_String(alignItems, serializer);
          sse_encode_opt_box_autoadd_f_64(gapRow, serializer);
          sse_encode_opt_box_autoadd_f_64(gapColumn, serializer);
          sse_encode_opt_box_autoadd_f_64(width, serializer);
          sse_encode_opt_box_autoadd_f_64(height, serializer);
          sse_encode_opt_box_autoadd_f_64(minWidth, serializer);
          sse_encode_opt_box_autoadd_f_64(minHeight, serializer);
          sse_encode_opt_box_autoadd_f_64(maxWidth, serializer);
          sse_encode_opt_box_autoadd_f_64(maxHeight, serializer);
          sse_encode_opt_box_autoadd_f_64(flexGrow, serializer);
          sse_encode_opt_box_autoadd_f_64(flexShrink, serializer);
          sse_encode_opt_box_autoadd_f_64(paddingTop, serializer);
          sse_encode_opt_box_autoadd_f_64(paddingRight, serializer);
          sse_encode_opt_box_autoadd_f_64(paddingBottom, serializer);
          sse_encode_opt_box_autoadd_f_64(paddingLeft, serializer);
          sse_encode_opt_box_autoadd_f_64(marginTop, serializer);
          sse_encode_opt_box_autoadd_f_64(marginRight, serializer);
          sse_encode_opt_box_autoadd_f_64(marginBottom, serializer);
          sse_encode_opt_box_autoadd_f_64(marginLeft, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLayoutApiLayoutAddContainerConstMeta,
        argValues: [
          treeId,
          childrenIds,
          flexDirection,
          flexWrap,
          justifyContent,
          alignItems,
          gapRow,
          gapColumn,
          width,
          height,
          minWidth,
          minHeight,
          maxWidth,
          maxHeight,
          flexGrow,
          flexShrink,
          paddingTop,
          paddingRight,
          paddingBottom,
          paddingLeft,
          marginTop,
          marginRight,
          marginBottom,
          marginLeft,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLayoutApiLayoutAddContainerConstMeta =>
      const TaskConstMeta(
        debugName: "layout_add_container",
        argNames: [
          "treeId",
          "childrenIds",
          "flexDirection",
          "flexWrap",
          "justifyContent",
          "alignItems",
          "gapRow",
          "gapColumn",
          "width",
          "height",
          "minWidth",
          "minHeight",
          "maxWidth",
          "maxHeight",
          "flexGrow",
          "flexShrink",
          "paddingTop",
          "paddingRight",
          "paddingBottom",
          "paddingLeft",
          "marginTop",
          "marginRight",
          "marginBottom",
          "marginLeft",
        ],
      );

  @override
  BigInt crateApiLayoutApiLayoutAddNode({
    required int treeId,
    double? width,
    double? height,
    double? minWidth,
    double? minHeight,
    double? maxWidth,
    double? maxHeight,
    double? flexGrow,
    double? flexShrink,
    double? paddingTop,
    double? paddingRight,
    double? paddingBottom,
    double? paddingLeft,
    double? marginTop,
    double? marginRight,
    double? marginBottom,
    double? marginLeft,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(treeId, serializer);
          sse_encode_opt_box_autoadd_f_64(width, serializer);
          sse_encode_opt_box_autoadd_f_64(height, serializer);
          sse_encode_opt_box_autoadd_f_64(minWidth, serializer);
          sse_encode_opt_box_autoadd_f_64(minHeight, serializer);
          sse_encode_opt_box_autoadd_f_64(maxWidth, serializer);
          sse_encode_opt_box_autoadd_f_64(maxHeight, serializer);
          sse_encode_opt_box_autoadd_f_64(flexGrow, serializer);
          sse_encode_opt_box_autoadd_f_64(flexShrink, serializer);
          sse_encode_opt_box_autoadd_f_64(paddingTop, serializer);
          sse_encode_opt_box_autoadd_f_64(paddingRight, serializer);
          sse_encode_opt_box_autoadd_f_64(paddingBottom, serializer);
          sse_encode_opt_box_autoadd_f_64(paddingLeft, serializer);
          sse_encode_opt_box_autoadd_f_64(marginTop, serializer);
          sse_encode_opt_box_autoadd_f_64(marginRight, serializer);
          sse_encode_opt_box_autoadd_f_64(marginBottom, serializer);
          sse_encode_opt_box_autoadd_f_64(marginLeft, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLayoutApiLayoutAddNodeConstMeta,
        argValues: [
          treeId,
          width,
          height,
          minWidth,
          minHeight,
          maxWidth,
          maxHeight,
          flexGrow,
          flexShrink,
          paddingTop,
          paddingRight,
          paddingBottom,
          paddingLeft,
          marginTop,
          marginRight,
          marginBottom,
          marginLeft,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLayoutApiLayoutAddNodeConstMeta =>
      const TaskConstMeta(
        debugName: "layout_add_node",
        argNames: [
          "treeId",
          "width",
          "height",
          "minWidth",
          "minHeight",
          "maxWidth",
          "maxHeight",
          "flexGrow",
          "flexShrink",
          "paddingTop",
          "paddingRight",
          "paddingBottom",
          "paddingLeft",
          "marginTop",
          "marginRight",
          "marginBottom",
          "marginLeft",
        ],
      );

  @override
  void crateApiLayoutApiLayoutCompute({
    required int treeId,
    required BigInt rootId,
    required double width,
    required double height,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(treeId, serializer);
          sse_encode_u_64(rootId, serializer);
          sse_encode_f_64(width, serializer);
          sse_encode_f_64(height, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLayoutApiLayoutComputeConstMeta,
        argValues: [treeId, rootId, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLayoutApiLayoutComputeConstMeta =>
      const TaskConstMeta(
        debugName: "layout_compute",
        argNames: ["treeId", "rootId", "width", "height"],
      );

  @override
  Float64List crateApiLayoutApiLayoutGetResult({
    required int treeId,
    required BigInt nodeId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(treeId, serializer);
          sse_encode_u_64(nodeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLayoutApiLayoutGetResultConstMeta,
        argValues: [treeId, nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLayoutApiLayoutGetResultConstMeta =>
      const TaskConstMeta(
        debugName: "layout_get_result",
        argNames: ["treeId", "nodeId"],
      );

  @override
  Future<String> crateApiVnodeApiParseVnodeFromJs({required String jsCode}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jsCode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVnodeApiParseVnodeFromJsConstMeta,
        argValues: [jsCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVnodeApiParseVnodeFromJsConstMeta =>
      const TaskConstMeta(
        debugName: "parse_vnode_from_js",
        argNames: ["jsCode"],
      );

  @override
  Future<QBError> crateApiErrorApiQbErrorCompile({required String message}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qb_error,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiErrorApiQbErrorCompileConstMeta,
        argValues: [message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiErrorApiQbErrorCompileConstMeta =>
      const TaskConstMeta(debugName: "qb_error_compile", argNames: ["message"]);

  @override
  Future<QBError> crateApiErrorApiQbErrorRender({
    required String message,
    int? componentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          sse_encode_opt_box_autoadd_i_32(componentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qb_error,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiErrorApiQbErrorRenderConstMeta,
        argValues: [message, componentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiErrorApiQbErrorRenderConstMeta =>
      const TaskConstMeta(
        debugName: "qb_error_render",
        argNames: ["message", "componentId"],
      );

  @override
  Future<QBError> crateApiErrorApiQbErrorRuntime({
    required String message,
    int? componentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          sse_encode_opt_box_autoadd_i_32(componentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qb_error,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiErrorApiQbErrorRuntimeConstMeta,
        argValues: [message, componentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiErrorApiQbErrorRuntimeConstMeta =>
      const TaskConstMeta(
        debugName: "qb_error_runtime",
        argNames: ["message", "componentId"],
      );

  @override
  Future<RenderNode> crateApiPocRenderRenderFromJs({
    required String jsCode,
    required double viewportWidth,
    required double viewportHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jsCode, serializer);
          sse_encode_f_64(viewportWidth, serializer);
          sse_encode_f_64(viewportHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_node,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPocRenderRenderFromJsConstMeta,
        argValues: [jsCode, viewportWidth, viewportHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPocRenderRenderFromJsConstMeta =>
      const TaskConstMeta(
        debugName: "render_from_js",
        argNames: ["jsCode", "viewportWidth", "viewportHeight"],
      );

  @override
  Future<List<RenderNode>> crateApiVnodeApiRenderVnodeFromJs({
    required String jsCode,
    required double viewportWidth,
    required double viewportHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jsCode, serializer);
          sse_encode_f_64(viewportWidth, serializer);
          sse_encode_f_64(viewportHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_render_node,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVnodeApiRenderVnodeFromJsConstMeta,
        argValues: [jsCode, viewportWidth, viewportHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVnodeApiRenderVnodeFromJsConstMeta =>
      const TaskConstMeta(
        debugName: "render_vnode_from_js",
        argNames: ["jsCode", "viewportWidth", "viewportHeight"],
      );

  @override
  Future<List<RenderNode>> crateApiVnodeApiRenderVnodeFromJson({
    required String vnodeJson,
    required double viewportWidth,
    required double viewportHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vnodeJson, serializer);
          sse_encode_f_64(viewportWidth, serializer);
          sse_encode_f_64(viewportHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_render_node,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVnodeApiRenderVnodeFromJsonConstMeta,
        argValues: [vnodeJson, viewportWidth, viewportHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVnodeApiRenderVnodeFromJsonConstMeta =>
      const TaskConstMeta(
        debugName: "render_vnode_from_json",
        argNames: ["vnodeJson", "viewportWidth", "viewportHeight"],
      );

  @override
  String crateApiSimpleRustCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRustCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRustCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "rust_core_version", argNames: []);

  @override
  Future<String> crateApiErrorApiSafeCompileTemplate({
    required String template,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(template, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiErrorApiSafeCompileTemplateConstMeta,
        argValues: [template],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiErrorApiSafeCompileTemplateConstMeta =>
      const TaskConstMeta(
        debugName: "safe_compile_template",
        argNames: ["template"],
      );

  @override
  Future<PlatformInt64> crateApiSimpleSumToN({required PlatformInt64 n}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(n, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSumToNConstMeta,
        argValues: [n],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSumToNConstMeta =>
      const TaskConstMeta(debugName: "sum_to_n", argNames: ["n"]);

  @override
  Stream<int> crateApiSimpleTickStream({required int count}) {
    final sink = RustStreamSink<int>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_i_32_Sse(sink, serializer);
            sse_encode_i_32(count, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 38,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleTickStreamConstMeta,
          argValues: [sink, count],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleTickStreamConstMeta => const TaskConstMeta(
    debugName: "tick_stream",
    argNames: ["sink", "count"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<int> dco_decode_StreamSink_i_32_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RenderNode> dco_decode_list_render_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_render_node).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  QBError dco_decode_qb_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return QBError(
      source: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
      stack: dco_decode_opt_String(arr[2]),
      componentId: dco_decode_opt_box_autoadd_i_32(arr[3]),
      timestamp: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  RenderNode dco_decode_render_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return RenderNode(
      id: dco_decode_String(arr[0]),
      nodeType: dco_decode_String(arr[1]),
      text: dco_decode_opt_String(arr[2]),
      color: dco_decode_opt_String(arr[3]),
      x: dco_decode_f_64(arr[4]),
      y: dco_decode_f_64(arr[5]),
      width: dco_decode_f_64(arr[6]),
      height: dco_decode_f_64(arr[7]),
      fontSize: dco_decode_opt_box_autoadd_f_64(arr[8]),
      textColor: dco_decode_opt_String(arr[9]),
      events: dco_decode_list_String(arr[10]),
      children: dco_decode_list_render_node(arr[11]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<int> sse_decode_StreamSink_i_32_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RenderNode> sse_decode_list_render_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RenderNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_render_node(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QBError sse_decode_qb_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_source = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_stack = sse_decode_opt_String(deserializer);
    var var_componentId = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    return QBError(
      source: var_source,
      message: var_message,
      stack: var_stack,
      componentId: var_componentId,
      timestamp: var_timestamp,
    );
  }

  @protected
  RenderNode sse_decode_render_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_nodeType = sse_decode_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_color = sse_decode_opt_String(deserializer);
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    var var_width = sse_decode_f_64(deserializer);
    var var_height = sse_decode_f_64(deserializer);
    var var_fontSize = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_textColor = sse_decode_opt_String(deserializer);
    var var_events = sse_decode_list_String(deserializer);
    var var_children = sse_decode_list_render_node(deserializer);
    return RenderNode(
      id: var_id,
      nodeType: var_nodeType,
      text: var_text,
      color: var_color,
      x: var_x,
      y: var_y,
      width: var_width,
      height: var_height,
      fontSize: var_fontSize,
      textColor: var_textColor,
      events: var_events,
      children: var_children,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_i_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_render_node(
    List<RenderNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_render_node(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_qb_error(QBError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.source, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.stack, serializer);
    sse_encode_opt_box_autoadd_i_32(self.componentId, serializer);
    sse_encode_u_64(self.timestamp, serializer);
  }

  @protected
  void sse_encode_render_node(RenderNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.nodeType, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.color, serializer);
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
    sse_encode_f_64(self.width, serializer);
    sse_encode_f_64(self.height, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fontSize, serializer);
    sse_encode_opt_String(self.textColor, serializer);
    sse_encode_list_String(self.events, serializer);
    sse_encode_list_render_node(self.children, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
