// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `component_engine`, `ensure_component_engine`, `eval_sync_void`, `eval_sync`, `extract_raw_runtime`, `get_js_exception`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ComponentEngine`

/// 创建组件实例。
///
/// 注意: 传入的 JS 已经包含了 `JSON.stringify` 包装,
/// 所以这里直接执行即可，不需要再次包装。
Future<String> createComponent({required String jsCode}) =>
    RustLib.instance.api.crateApiComponentApiCreateComponent(jsCode: jsCode);

/// 获取组件当前 VNode 的 JSON 表示。
Future<String> getComponentVnode({required int componentId}) => RustLib
    .instance
    .api
    .crateApiComponentApiGetComponentVnode(componentId: componentId);

/// 调用组件方法，返回更新后的 VNode JSON。
Future<String> callComponentMethod({
  required int componentId,
  required String method,
  required String argsJson,
}) => RustLib.instance.api.crateApiComponentApiCallComponentMethod(
  componentId: componentId,
  method: method,
  argsJson: argsJson,
);

/// 在组件引擎中执行 JS 代码。
Future<String> evalComponentJs({required String code}) =>
    RustLib.instance.api.crateApiComponentApiEvalComponentJs(code: code);

/// 销毁组件实例。
Future<void> destroyComponent({required int componentId}) => RustLib
    .instance
    .api
    .crateApiComponentApiDestroyComponent(componentId: componentId);

/// 销毁组件引擎。
Future<void> destroyComponentEngine() =>
    RustLib.instance.api.crateApiComponentApiDestroyComponentEngine();
