// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 编译 Vue 模板为 JS render 函数代码。
///
/// # 参数
/// - `template`: Vue 模板字符串
///
/// # 返回
/// JS render 函数代码字符串。
///
/// # 示例
/// ```rust
/// let template = "<view><text>{{ message }}</text></view>";
/// let render_fn = compile_template(template.to_string()).unwrap();
/// // render_fn 包含 "function render() { ... }"
/// ```
Future<String> compileTemplate({required String template}) =>
    RustLib.instance.api.crateApiCompilerApiCompileTemplate(template: template);

/// 编译模板 + script，返回完整的组件创建 JS 代码。
///
/// 将模板编译为 render 函数，与 script 中的组件选项合并，
/// 生成可直接传给 `create_component` 的 JS 代码。
///
/// # 参数
/// - `template`: Vue 模板字符串
/// - `script`: JS script 内容 (组件选项对象字面量，如 `{ data: ..., methods: ... }`)
///
/// # 返回
/// 可执行的 JS 代码字符串，调用后返回 `{ id, vnode }` JSON。
///
/// # 示例
/// ```rust
/// let template = "<view @tap=\"increment\"><text>{{ count }}</text></view>";
/// let script = "{ data: function() { return { count: 0 }; }, methods: { increment: function() { this.count++; } } }";
/// let js = compile_and_create_component(template.to_string(), script.to_string()).unwrap();
/// ```
Future<String> compileAndCreateComponent({
  required String template,
  required String script,
}) => RustLib.instance.api.crateApiCompilerApiCompileAndCreateComponent(
  template: template,
  script: script,
);
