// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `now_ms`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 安全执行模板编译，返回结构化错误。
Future<String> safeCompileTemplate({required String template}) => RustLib
    .instance
    .api
    .crateApiErrorApiSafeCompileTemplate(template: template);

/// 获取最近的 JS 引擎错误列表 (JSON)。
Future<String> getRecentErrors() =>
    RustLib.instance.api.crateApiErrorApiGetRecentErrors();

/// 七巧板结构化错误。
class QBError {
  /// 错误来源: "compile" / "runtime" / "render" / "network"
  final String source;

  /// 错误消息。
  final String message;

  /// JS 堆栈 (可选)。
  final String? stack;

  /// 关联的组件 ID (可选)。
  final int? componentId;

  /// 时间戳 (Unix ms)。
  final BigInt timestamp;

  const QBError({
    required this.source,
    required this.message,
    this.stack,
    this.componentId,
    required this.timestamp,
  });

  static Future<QBError> compile({required String message}) =>
      RustLib.instance.api.crateApiErrorApiQbErrorCompile(message: message);

  static Future<QBError> render({required String message, int? componentId}) =>
      RustLib.instance.api.crateApiErrorApiQbErrorRender(
        message: message,
        componentId: componentId,
      );

  static Future<QBError> runtime({required String message, int? componentId}) =>
      RustLib.instance.api.crateApiErrorApiQbErrorRuntime(
        message: message,
        componentId: componentId,
      );

  @override
  int get hashCode =>
      source.hashCode ^
      message.hashCode ^
      stack.hashCode ^
      componentId.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QBError &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          message == other.message &&
          stack == other.stack &&
          componentId == other.componentId &&
          timestamp == other.timestamp;
}
