// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `store`, `value_to_string`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngineInstance`, `EngineStore`

/// 创建一个新的 JS 引擎实例 (同步)。
Future<int> createJsEngine({int? memoryLimitMb, int? maxStackSizeKb}) =>
    RustLib.instance.api.crateApiJsEngineCreateJsEngine(
      memoryLimitMb: memoryLimitMb,
      maxStackSizeKb: maxStackSizeKb,
    );

/// 在指定引擎中执行 JS 代码 (同步)。
Future<String> evalJs({required int engineId, required String code}) =>
    RustLib.instance.api.crateApiJsEngineEvalJs(engineId: engineId, code: code);

/// 销毁指定的 JS 引擎实例。
Future<void> destroyJsEngine({required int engineId}) =>
    RustLib.instance.api.crateApiJsEngineDestroyJsEngine(engineId: engineId);

/// 获取当前活跃的引擎数量（调试用途）。
int activeEngineCount() =>
    RustLib.instance.api.crateApiJsEngineActiveEngineCount();
