// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_style`, `store`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LayoutStore`

/// 创建一个新的布局树实例。
///
/// 返回布局树 ID。
int createLayoutTree() =>
    RustLib.instance.api.crateApiLayoutApiCreateLayoutTree();

/// 在布局树中添加一个叶子节点。
///
/// 返回节点 ID (u64)。
BigInt layoutAddNode({
  required int treeId,
  double? width,
  double? height,
  double? minWidth,
  double? minHeight,
  double? maxWidth,
  double? maxHeight,
  double? flexGrow,
  double? flexShrink,
  double? paddingTop,
  double? paddingRight,
  double? paddingBottom,
  double? paddingLeft,
  double? marginTop,
  double? marginRight,
  double? marginBottom,
  double? marginLeft,
}) => RustLib.instance.api.crateApiLayoutApiLayoutAddNode(
  treeId: treeId,
  width: width,
  height: height,
  minWidth: minWidth,
  minHeight: minHeight,
  maxWidth: maxWidth,
  maxHeight: maxHeight,
  flexGrow: flexGrow,
  flexShrink: flexShrink,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  paddingLeft: paddingLeft,
  marginTop: marginTop,
  marginRight: marginRight,
  marginBottom: marginBottom,
  marginLeft: marginLeft,
);

/// 在布局树中添加一个容器节点。
BigInt layoutAddContainer({
  required int treeId,
  required Uint64List childrenIds,
  String? flexDirection,
  String? flexWrap,
  String? justifyContent,
  String? alignItems,
  double? gapRow,
  double? gapColumn,
  double? width,
  double? height,
  double? minWidth,
  double? minHeight,
  double? maxWidth,
  double? maxHeight,
  double? flexGrow,
  double? flexShrink,
  double? paddingTop,
  double? paddingRight,
  double? paddingBottom,
  double? paddingLeft,
  double? marginTop,
  double? marginRight,
  double? marginBottom,
  double? marginLeft,
}) => RustLib.instance.api.crateApiLayoutApiLayoutAddContainer(
  treeId: treeId,
  childrenIds: childrenIds,
  flexDirection: flexDirection,
  flexWrap: flexWrap,
  justifyContent: justifyContent,
  alignItems: alignItems,
  gapRow: gapRow,
  gapColumn: gapColumn,
  width: width,
  height: height,
  minWidth: minWidth,
  minHeight: minHeight,
  maxWidth: maxWidth,
  maxHeight: maxHeight,
  flexGrow: flexGrow,
  flexShrink: flexShrink,
  paddingTop: paddingTop,
  paddingRight: paddingRight,
  paddingBottom: paddingBottom,
  paddingLeft: paddingLeft,
  marginTop: marginTop,
  marginRight: marginRight,
  marginBottom: marginBottom,
  marginLeft: marginLeft,
);

/// 计算布局。
void layoutCompute({
  required int treeId,
  required BigInt rootId,
  required double width,
  required double height,
}) => RustLib.instance.api.crateApiLayoutApiLayoutCompute(
  treeId: treeId,
  rootId: rootId,
  width: width,
  height: height,
);

/// 获取节点布局结果，返回 [x, y, width, height]。
Float64List layoutGetResult({required int treeId, required BigInt nodeId}) =>
    RustLib.instance.api.crateApiLayoutApiLayoutGetResult(
      treeId: treeId,
      nodeId: nodeId,
    );

/// 销毁布局树。
void destroyLayoutTree({required int treeId}) =>
    RustLib.instance.api.crateApiLayoutApiDestroyLayoutTree(treeId: treeId);
