// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_layout_node`, `collect_render_tree`, `estimate_text_width`, `is_wide_char`, `parse_style`, `parse_dimension_value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NodeMeta`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 执行 JS 代码并返回渲染树（单根节点，树结构）。
///
/// 每次调用创建独立的 **同步** QuickJS 引擎 (无 tokio/async)。
/// 返回的 RenderNode 是一棵树，x/y 为相对于父节点的坐标。
Future<RenderNode> renderFromJs({
  required String jsCode,
  required double viewportWidth,
  required double viewportHeight,
}) => RustLib.instance.api.crateApiPocRenderRenderFromJs(
  jsCode: jsCode,
  viewportWidth: viewportWidth,
  viewportHeight: viewportHeight,
);

/// 销毁 PoC 引擎 (兼容旧 API — 现在是 no-op)。
Future<void> destroyPocEngine() =>
    RustLib.instance.api.crateApiPocRenderDestroyPocEngine();

/// 单个渲染节点的完整信息（树结构）。
///
/// x/y 为相对父节点的坐标，children 保持树形结构。
/// `node_type` 支持: "view", "text", "scroll-view", "image", "button", "input",
/// "icon", "rich-text", "checkbox", "checkbox-group", "form", "picker",
/// "picker-view", "radio", "radio-group", "slider", "switch", "textarea",
/// "draggable-sheet", "grid-builder", "grid-view", "list-builder",
/// "list-view", "navigator", "canvas", "swiper"
class RenderNode {
  final String id;
  final String nodeType;
  final String? text;
  final String? color;
  final double x;
  final double y;
  final double width;
  final double height;
  final double? fontSize;
  final String? textColor;
  final String? fontWeight;
  final double? borderRadius;
  final double? opacity;
  final Map<String, String> extraProps;
  final List<String> events;
  final List<RenderNode> children;

  const RenderNode({
    required this.id,
    required this.nodeType,
    this.text,
    this.color,
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    this.fontSize,
    this.textColor,
    this.fontWeight,
    this.borderRadius,
    this.opacity,
    this.extraProps = const {},
    required this.events,
    required this.children,
  });

  /// 从 extraProps 获取组件特有属性。
  String? getExtraProp(String key) => extraProps[key];

  /// 从 extraProps 获取布尔值属性。
  bool getExtraPropBool(String key, {bool defaultValue = false}) {
    final val = extraProps[key];
    if (val == null) return defaultValue;
    return val == 'true' || val == '1';
  }

  /// 从 extraProps 获取数字属性。
  double? getExtraPropDouble(String key) {
    final val = extraProps[key];
    if (val == null) return null;
    return double.tryParse(val);
  }

  /// 从 extraProps 获取整数属性。
  int? getExtraPropInt(String key) {
    final val = extraProps[key];
    if (val == null) return null;
    return int.tryParse(val);
  }

  @override
  int get hashCode =>
      id.hashCode ^
      nodeType.hashCode ^
      text.hashCode ^
      color.hashCode ^
      x.hashCode ^
      y.hashCode ^
      width.hashCode ^
      height.hashCode ^
      fontSize.hashCode ^
      textColor.hashCode ^
      fontWeight.hashCode ^
      borderRadius.hashCode ^
      opacity.hashCode ^
      extraProps.hashCode ^
      events.hashCode ^
      children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nodeType == other.nodeType &&
          text == other.text &&
          color == other.color &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          fontSize == other.fontSize &&
          textColor == other.textColor &&
          fontWeight == other.fontWeight &&
          borderRadius == other.borderRadius &&
          opacity == other.opacity &&
          events == other.events &&
          children == other.children;
}
