// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 返回一条问候消息。
///
/// 这是最简单的同步调用示例，用于验证 Dart → Rust FFI 链路连通性。
///
/// # 参数
/// - `name`: 被问候者的名字
///
/// # 返回
/// 格式化的问候字符串
///
/// # 示例 (Dart 侧)
/// ```dart
/// final message = greet(name: "七巧板");
/// // => "Hello, 七巧板! 来自 Rust 🦀"
/// ```
String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// 返回 Rust 侧的版本信息。
///
/// 用于在 Dart 侧展示 Rust core 的版本号，方便调试和版本追踪。
String rustCoreVersion() =>
    RustLib.instance.api.crateApiSimpleRustCoreVersion();

/// 异步累加计算。
///
/// 模拟一个耗时的 Rust 计算任务。在独立线程执行，不会阻塞 Dart UI 线程。
///
/// # 参数
/// - `n`: 累加上限（计算 1 + 2 + ... + n）
///
/// # 返回
/// 累加结果
Future<PlatformInt64> sumToN({required PlatformInt64 n}) =>
    RustLib.instance.api.crateApiSimpleSumToN(n: n);

/// 每秒推送一个递增整数，用于验证 Stream 通信模式。
///
/// 此函数会在独立线程中持续运行，通过 `StreamSink` 向 Dart 侧推送数据。
/// Dart 侧会收到一个 `Stream<i32>`，可通过 `listen` 订阅。
///
/// # 参数
/// - `sink`: 由 `flutter_rust_bridge` 自动注入的 Stream 推送通道
/// - `count`: 推送总次数（推送完毕后 Stream 自动关闭）
///
/// # 示例 (Dart 侧)
/// ```dart
/// tickStream(count: 10).listen((tick) {
///   print('Tick: $tick');
/// });
/// ```
Stream<int> tickStream({required int count}) =>
    RustLib.instance.api.crateApiSimpleTickStream(count: count);
