// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'poc_render.dart';

// These functions are ignored because they are not marked as `pub`: `collect_render_nodes`, `ensure_engine`, `eval_sync`, `extract_raw_runtime`, `vnode_engine`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `VNodeEngine`

/// 执行 JS 代码并返回 VNode 树的 JSON 表示。
Future<String> parseVnodeFromJs({required String jsCode}) =>
    RustLib.instance.api.crateApiVnodeApiParseVnodeFromJs(jsCode: jsCode);

/// 对两个 VNode 树执行 Diff，返回 PatchSet 的 JSON 表示。
Future<String> diffVnodes({required String oldJson, required String newJson}) =>
    RustLib.instance.api.crateApiVnodeApiDiffVnodes(
      oldJson: oldJson,
      newJson: newJson,
    );

/// 从 VNode JSON 计算布局，返回布局结果 JSON。
Future<String> computeLayoutFromVnode({
  required String vnodeJson,
  required double width,
  required double height,
}) => RustLib.instance.api.crateApiVnodeApiComputeLayoutFromVnode(
  vnodeJson: vnodeJson,
  width: width,
  height: height,
);

/// 完整管线: JS → VNode → Layout → 渲染数据。
Future<List<RenderNode>> renderVnodeFromJs({
  required String jsCode,
  required double viewportWidth,
  required double viewportHeight,
}) => RustLib.instance.api.crateApiVnodeApiRenderVnodeFromJs(
  jsCode: jsCode,
  viewportWidth: viewportWidth,
  viewportHeight: viewportHeight,
);

/// 分发用户交互事件到 JS 处理函数。
Future<String> dispatchEvent({required String eventJson}) =>
    RustLib.instance.api.crateApiVnodeApiDispatchEvent(eventJson: eventJson);

/// 在 JS 引擎中执行代码。
Future<String> evalVnodeJs({required String code}) =>
    RustLib.instance.api.crateApiVnodeApiEvalVnodeJs(code: code);

/// 销毁 VNode API 引擎。
Future<void> destroyVnodeEngine() =>
    RustLib.instance.api.crateApiVnodeApiDestroyVnodeEngine();

/// 从 VNode JSON 直接生成 RenderNode 列表。
Future<List<RenderNode>> renderVnodeFromJson({
  required String vnodeJson,
  required double viewportWidth,
  required double viewportHeight,
}) => RustLib.instance.api.crateApiVnodeApiRenderVnodeFromJson(
  vnodeJson: vnodeJson,
  viewportWidth: viewportWidth,
  viewportHeight: viewportHeight,
);
